[package]
name                  = "oxc_query"
version               = "0.0.7"
publish               = true
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_ast         = { workspace = true }
oxc_semantic    = { workspace = true }
oxc_span        = { workspace = true }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
url             = { workspace = true }

trustfall = "0.5.0"
enum-as-inner = "0.6.0"

[dev_dependencies]
oxc_allocator   = { workspace = true }
oxc_parser   = { workspace = true }

