[package]
name                   = "oxc"
version                = "0.2.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[dependencies]
oxc_allocator   = { workspace = true }
oxc_ast         = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_index       = { workspace = true }
oxc_parser      = { workspace = true }
oxc_span        = { workspace = true }
oxc_syntax      = { workspace = true }
oxc_semantic    = { workspace = true, optional = true }
oxc_formatter   = { workspace = true, optional = true }
oxc_ast_lower   = { workspace = true, optional = true }
oxc_hir         = { workspace = true, optional = true }
oxc_minifier    = { workspace = true, optional = true }

[features]
formatter = ["oxc_formatter"]
semantic  = ["oxc_semantic"]
minifier  = ["oxc_hir", "oxc_ast_lower", "oxc_minifier"]
