[package]
name                   = "oxc"
version                = "0.5.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[lib]
test    = false
doctest = false

[dependencies]
oxc_allocator   = { workspace = true }
oxc_ast         = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_index       = { workspace = true }
oxc_parser      = { workspace = true }
oxc_span        = { workspace = true }
oxc_syntax      = { workspace = true }
oxc_semantic    = { workspace = true, optional = true }
oxc_transformer = { workspace = true, optional = true }
oxc_minifier    = { workspace = true, optional = true }
oxc_codegen     = { workspace = true, optional = true }

[features]
serde       = ["oxc_ast/serde", "oxc_semantic/serde"]
semantic    = ["oxc_semantic"]
transformer = ["oxc_transformer"]
minifier    = ["oxc_minifier"]
codegen     = ["oxc_codegen"]
wasm        = ["oxc_ast/wasm", "serde", "oxc_semantic?/wasm", "oxc_span/wasm", "oxc_syntax/wasm"]
