[package]
name                  = "oxc"
version               = "0.0.7"
publish               = true
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_allocator   = { workspace = true }
oxc_ast         = { workspace = true }
oxc_ast_lower   = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_formatter   = { workspace = true }
oxc_hir         = { workspace = true }
oxc_index       = { workspace = true }
oxc_minifier    = { workspace = true }
oxc_parser      = { workspace = true }
oxc_semantic    = { workspace = true }
oxc_span        = { workspace = true }
oxc_syntax      = { workspace = true }
