[package]
name                   = "oxc"
version                = "0.27.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src"]

[lints]
workspace = true

[lib]
test    = false
doctest = false

[[example]]
name              = "compiler"
path              = "examples/compiler.rs"
required-features = ["full"]

[dependencies]
oxc_allocator             = { workspace = true }
oxc_ast                   = { workspace = true }
oxc_diagnostics           = { workspace = true }
oxc_index                 = { workspace = true }
oxc_parser                = { workspace = true }
oxc_span                  = { workspace = true }
oxc_syntax                = { workspace = true }
oxc_semantic              = { workspace = true, optional = true }
oxc_transformer           = { workspace = true, optional = true }
oxc_minifier              = { workspace = true, optional = true }
oxc_mangler               = { workspace = true, optional = true }
oxc_codegen               = { workspace = true, optional = true }
oxc_sourcemap             = { workspace = true, optional = true }
oxc_isolated_declarations = { workspace = true, optional = true }

[features]
full = ["codegen", "mangler", "minifier", "semantic", "transformer"]

semantic    = ["oxc_semantic"]
transformer = ["oxc_transformer"]
minifier    = ["oxc_mangler", "oxc_minifier"]
codegen     = ["oxc_codegen"]
mangler     = ["oxc_mangler"]

serialize = ["oxc_ast/serialize", "oxc_semantic?/serialize", "oxc_span/serialize", "oxc_syntax/serialize"]

sourcemap            = ["oxc_sourcemap"]
sourcemap_concurrent = ["oxc_sourcemap/concurrent", "sourcemap"]

isolated_declarations = ["oxc_isolated_declarations"]

wasm = ["oxc_transformer/wasm"]
