[package]
name = "oxc_parser"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_allocator = { path = "../oxc_allocator" }
oxc_ast = { path = "../oxc_ast" }
oxc_diagnostics = { path = "../oxc_diagnostics" }

bitflags = { workspace = true }
rustc-hash = { workspace = true }

unicode-id-start = "1.0.3"
num-bigint = "0.4.3"

[dev-dependencies]
miette = { workspace = true, features = ["fancy"] }
oxc_ast = { path = "../oxc_ast", features = ["serde_json"] }
serde_json = { workspace = true }
