[package]
name                   = "oxc_parser"
version                = "0.24.2"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/examples", "/src"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator     = { workspace = true }
oxc_span          = { workspace = true }
oxc_ast           = { workspace = true }
oxc_syntax        = { workspace = true }
oxc_diagnostics   = { workspace = true }
oxc_regexp_parser = { workspace = true }

assert-unchecked = { workspace = true }
bitflags         = { workspace = true }
num-bigint       = { workspace = true }
num-traits       = { workspace = true }
rustc-hash       = { workspace = true }
seq-macro        = { workspace = true }

memchr = { workspace = true }

[dev-dependencies]
oxc_ast    = { workspace = true, features = ["serialize"] }
serde_json = { workspace = true }
ouroboros  = { workspace = true } # for `multi-thread` example

[features]
# Expose Lexer for benchmarks
benchmarking = []
