[package]
name = "oxc_parser"
version = "0.0.3"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[lib]
# We don't use doc tests because it's too slow
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_diagnostics = { workspace = true }

bitflags = { workspace = true }
rustc-hash = { workspace = true }

unicode-id-start = "1.1.0"
num-bigint = "0.4.3"

[dev-dependencies]
oxc_ast = { workspace = true, features = ["serde"] }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
serde_json = { workspace = true }
