version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Boshen"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Boshen"

  # Enable when we have more resources
  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   assignees:
  #     - "Boshen"
