include = ["Cargo.toml", "crates/*/*.toml", "tasks/*/*.toml", "editor/*/*.toml", "napi/*/*.toml", "wasm/*/*.toml"]

[formatting]
align_entries = true
column_width = 120
align_comments = false
reorder_arrays = true
