# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "**/*.snap",
  "**/*/CHANGELOG.md",
  "crates/oxc_linter/fixtures",
  "crates/oxc_linter/src/rules/eslint/no_unused_vars/ignored.rs",
  "crates/oxc_linter/src/rules/eslint/no_unused_vars/options.rs",
  "crates/oxc_linter/src/rules/eslint/no_unused_vars/tests/eslint.rs",
  "crates/oxc_linter/src/rules/jsx_a11y/aria_props.rs",
  "crates/oxc_linter/src/rules/jsx_a11y/img_redundant_alt.rs",
  "crates/oxc_linter/src/rules/react/no_unknown_property.rs",
  "crates/oxc_parser/src/lexer/byte_handlers.rs",
  "crates/oxc_syntax/src/xml_entities.rs",
  "pnpm-lock.yaml",
  "tasks/coverage/babel",
  "tasks/coverage/test262",
  "tasks/coverage/typescript",
  "tasks/coverage/snapshots",
  "tasks/prettier_conformance/prettier",
  "tasks/prettier_conformance/snapshots",
  "tasks/transform_conformance/tests/**/output.js",
  "tasks/transform_conformance/overrides",
  "tasks/transform_conformance/snapshots",
  "npm/oxc-wasm/oxc_wasm.js",
  "napi/minify/test/terser.test.ts",
]

[default]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[default.extend-words]
trivias = "trivias"
trivia = "trivia"
xdescribe = "xdescribe"
seeked = "seeked"
labeledby = "labeledby"
hashi = "hashi"
inferrable = "inferrable"

[default.extend-identifiers]
IIFEs = "IIFEs"
allowIIFEs = "allowIIFEs"
