# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "tasks/coverage/test262",
  "tasks/coverage/babel",
  "tasks/coverage/typescript",
  "tasks/prettier_conformance/prettier",
  "crates/oxc_parser/src/lexer/byte_handlers.rs",
  "crates/oxc_linter/fixtures",
  "crates/oxc_linter/src/rules/jsx_a11y/img_redundant_alt.rs",
  "crates/oxc_linter/src/rules/react/no_unknown_property.rs",
  "crates/oxc_syntax/src/xml_entities.rs",
  "**/*.snap",
  "pnpm-lock.yaml",
  "**/*/CHANGELOG.md",
]

[default.extend-words]
trivias = "trivias"
trivia = "trivia"
xdescribe = "xdescribe"
seeked = "seeked"
labeledby = "labeledby"

[default.extend-identifiers]
IIFEs = "IIFEs"
