# https://github.com/crate-ci/typos
# cargo install typos-cli
# typos

[files]
extend-exclude = [
  "tasks/coverage/test262",
  "tasks/coverage/babel",
  "tasks/coverage/typescript",
  "crates/oxc_linter/tests",
  "**/*.snap",
  "pnpm-lock.yaml",
]

[default.extend-words]
trivias = "trivias"
trivia = "trivia"
xdescribe = "xdescribe"
