[jobs.example]
command = ["just", "run-example"]
allow_warnings = true
need_stdout = true

[jobs.oxlint]
command = ["cargo", "--color", "always", "run", "-p", "oxlint"]
allow_warnings = true
need_stdout = true

[jobs.wasm]
command = ["just", "build-wasm", "dev"]
allow_warnings = true
need_stdout = true
