# Configuration file for [cargo release oxc](https://github.com/oxc-project/cargo-release-oxc)

# Release `--name crates`
[[releases]]
name = "crates"
versioned_files = [
  "Cargo.toml",
  "napi/oxc-parser/package.json",
  "napi/oxc-transform/package.json",
  "napi/oxc-minify/package.json",
  "npm/oxc-types/package.json",
  "npm/runtime/package.json",
  "wasm/parser/package.json",
]

[[releases]]
name = "oxlint"
scopes_for_breaking_change = ["lint"]
versioned_files = [
  "apps/oxlint/Cargo.toml",
  "crates/oxc_linter/Cargo.toml",
  "editors/vscode/package.json",
  "npm/oxlint/package.json",
  "crates/oxc_language_server/Cargo.toml",
]
