[package]
name                   = "oxc_language_server"
version                = "0.0.1"
publish                = false
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[[bin]]
name = "oxc_language_server"
test = false

[dependencies]
oxc_allocator   = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_linter      = { workspace = true }
oxc_parser      = { workspace = true }
oxc_semantic    = { workspace = true }
oxc_span        = { workspace = true }
dashmap         = { workspace = true }
futures         = { workspace = true }
ignore          = { workspace = true, features = ["simd-accel"] }
ropey           = { workspace = true }
tokio           = { workspace = true, features = ["full"] }
tower-lsp       = { workspace = true, features = ["proposed"] }
serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
log             = { workspace = true }
globset         = { workspace = true }
env_logger      = { workspace = true, features = ["humantime"] }
