[package]
name              = "oxc_minsize"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[dependencies]
oxc_allocator   = { workspace = true }
oxc_parser      = { workspace = true }
oxc_ast         = { workspace = true }
oxc_printer     = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_semantic    = { workspace = true }

oxc_tasks_common = { workspace = true }
flate2           = { workspace = true }

humansize = "2.1.3"
