[package]
name              = "oxc_minsize"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[dependencies]
oxc_span     = { workspace = true }
oxc_minifier = { workspace = true }

oxc_tasks_common = { workspace = true }
flate2           = { workspace = true }

humansize = "2.1.3"
brotlic          = "0.8.1"
