[package]
name              = "oxc_minsize"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
oxc_span      = { workspace = true }
oxc_allocator = { workspace = true }
oxc_parser    = { workspace = true }
oxc_codegen   = { workspace = true }
oxc_minifier  = { workspace = true }

oxc_tasks_common = { workspace = true }
flate2           = { workspace = true }

humansize = "2.1.3"
brotlic   = "0.8.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { workspace = true }
