[package]
name = "oxc_minsize"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
test = false
doctest = false

[[bin]]
name = "oxc_minsize"
test = false
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_codegen = { workspace = true }
oxc_minifier = { workspace = true }
oxc_parser = { workspace = true }
oxc_semantic = { workspace = true }
oxc_span = { workspace = true }
oxc_transformer = { workspace = true }

flate2 = { workspace = true }
oxc_tasks_common = { workspace = true }

cow-utils = { workspace = true }
humansize = { workspace = true }
rustc-hash = { workspace = true }
similar-asserts = { workspace = true }
