[package]
name = "oxc_linter_codegen"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "oxc_linter_codegen"
test = false
doctest = false

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
project-root = { workspace = true }
quote = { workspace = true }
rustc-hash = { workspace = true }
syn = { workspace = true, features = ["full", "visit", "parsing"] }
