[package]
name = "oxc_prettier_conformance"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[bin]]
name = "oxc_prettier_conformance"
path = "src/main.rs"
test = false
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_parser = { workspace = true }
oxc_prettier = { workspace = true }
oxc_span = { workspace = true }
oxc_tasks_common = { workspace = true }

cow-utils = { workspace = true }
pico-args = { workspace = true }
rustc-hash = { workspace = true }
similar = { workspace = true }
walkdir = { workspace = true }
