[package]
name              = "oxc_ast_codegen"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[lints]
workspace = true


[[bin]]
name = "oxc_ast_codegen"
test = false

[dependencies]
syn = { workspace = true, features = [
  "clone-impls",
  "derive",
  "extra-traits",
  "full",
  "parsing",
  "printing",
  "proc-macro",
] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
regex = { workspace = true }
prettyplease = { workspace = true }
lazy_static = { workspace = true }
