[package]
name                   = "oxc_mangler"
version                = "0.22.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/examples", "/src"]

[lints]
workspace = true

[lib]
test    = false
doctest = false

[dependencies]
oxc_span     = { workspace = true }
oxc_ast      = { workspace = true }
oxc_semantic = { workspace = true }
oxc_index    = { workspace = true }
itertools    = { workspace = true }

[dev-dependencies]
oxc_codegen   = { workspace = true }
oxc_parser    = { workspace = true }
oxc_span      = { workspace = true }
oxc_allocator = { workspace = true }
insta         = { workspace = true }
