[package]
name = "website_formatter"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "website_formatter"
doctest = false

[dependencies]
bpaf = { workspace = true, features = ["docgen"] }
oxc_formatter = { workspace = true }
oxfmt = { workspace = true }
pico-args = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
website_common = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["bpaf"]
