[package]
name                  = "oxc_semantic2"
version               = "0.0.0"
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_span   = { workspace = true }
oxc_index  = { workspace = true }
oxc_syntax = { workspace = true }

bitflags   = { workspace = true }
rustc-hash = { workspace = true }
indexmap   = { workspace = true }
