[package]
name                   = "oxc_diagnostics"
version                = "0.1.1"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[dependencies]
thiserror = { workspace = true }
miette    = { workspace = true }

unicode-width = "0.1.10"
owo-colors    = { version = "3.5.0" }
textwrap      = { version = "=0.16.0" } # need to sync with miette
is-terminal   = { version = "0.4.9" }
