[package]
name = "oxc_formatter"
version = "0.4.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/examples", "/src"]
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_data_structures = { workspace = true, features = ["stack"] }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true }

cow-utils = { workspace = true }
json-strip-comments = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
unicode-width = "0.2"

[dev-dependencies]
insta = { workspace = true }
oxc_parser = { workspace = true }
pico-args = { workspace = true }
project-root = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
oxc_span = { workspace = true }
