[package]
name = "website_linter"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "website_linter"
doctest = false

[dependencies]
bpaf = { workspace = true, features = ["docgen"] }
itertools = { workspace = true }
oxc_linter = { workspace = true, features = ["ruledocs"] }
oxlint = { path = "../../apps/oxlint", default-features = false }
pico-args = { workspace = true }
project-root = { workspace = true }
schemars = { workspace = true }
website_common = { path = "../website_common" }

[dev-dependencies]
insta = { workspace = true }
markdown = { workspace = true }
oxc_allocator = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["bpaf"]
