contact_links:
  - name: Github discussions
    url: https://github.com/oxc-project/oxc/discussions
    about: For general discussions.

  - name: Discord server
    url: https://discord.gg/9uXCAwqQZW
    about: For lightweight questions.

  - name: Website issues
    url: https://github.com/oxc-project/website/issues
    about: For website issues other than Oxlint rule documentation. For Oxlint rule documentation issues, please file them in this repository.

  - name: VS Code extension issues
    url: https://github.com/oxc-project/oxc-vscode/issues
    about: For issues with the Oxc VS Code extension.
