[package]
name = "oxc_ast"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
oxc_allocator = { path = "../oxc_allocator" }

bitflags = { workspace = true }
compact_str = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
miette = { workspace = true }

num-bigint = "0.4.3"
ryu-js = "0.2.2"
ordered-float = { version = "3.4.0", features = ["serde"] }
