[package]
name                   = "oxc_ast"
version                = "0.1.0"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[features]
default = []
serde   = ["dep:serde", "dep:serde_json", "dep:ryu-js", "oxc_span/serde", "oxc_syntax/serde"]

[dependencies]
oxc_allocator = { workspace = true }
oxc_span      = { workspace = true }
oxc_syntax    = { workspace = true }
oxc_index     = { workspace = true }

bitflags   = { workspace = true }
rustc-hash = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
ryu-js     = { workspace = true, optional = true }
