[package]
name                  = "oxc_ast"
version               = "0.0.6"
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_allocator = { workspace = true }
oxc_span      = { workspace = true }

bitflags      = { workspace = true }
thiserror     = { workspace = true }
rustc-hash    = { workspace = true }
num-bigint    = { workspace = true }
ordered-float = { workspace = true }

serde      = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
ryu-js     = { workspace = true, optional = true }

[features]
default = []
serde   = ["dep:serde", "dep:serde_json", "dep:ryu-js", "ordered-float/serde", "oxc_span/serde"]
