[package]
name                   = "oxc_codegen"
version                = "0.13.1"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_ast       = { workspace = true }
oxc_span      = { workspace = true }
oxc_allocator = { workspace = true }
oxc_syntax    = { workspace = true }
oxc_sourcemap = { workspace = true }
bitflags      = { workspace = true }
once_cell     = { workspace = true }
daachorse     = { workspace = true }
rustc-hash    = { workspace = true }
[dev-dependencies]
oxc_parser = { workspace = true }
base64     = { workspace = true }
