[package]
name                  = "oxc_minifier"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_allocator = { workspace = true }
oxc_span      = { workspace = true }
oxc_parser    = { workspace = true }
oxc_ast       = { workspace = true }
oxc_ast_lower = { workspace = true }
oxc_hir       = { workspace = true }
oxc_semantic2 = { workspace = true }
oxc_syntax    = { workspace = true }

[dev-dependencies]
walkdir = { workspace = true }
pico-args = { workspace = true }

[target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dev-dependencies]
mimalloc = { workspace = true }
