[package]
name                   = "oxc_minifier"
version                = "0.10.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src", "/examples"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_span      = { workspace = true }
oxc_ast       = { workspace = true }
oxc_semantic  = { workspace = true }
oxc_syntax    = { workspace = true }
oxc_index     = { workspace = true }

num-bigint = { workspace = true }
itertools  = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
oxc_parser  = { workspace = true }
oxc_codegen = { workspace = true }

insta     = { workspace = true }
walkdir   = { workspace = true }
pico-args = { workspace = true }
