[package]
name                   = "oxc_transformer"
version                = "0.16.2"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/examples", "/src"]

[lints]
workspace = true

[lib]
test    = false
doctest = false

[dependencies]
oxc_ast         = { workspace = true }
oxc_span        = { workspace = true }
oxc_allocator   = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_syntax      = { workspace = true, features = ["to_js_string"] }
oxc_traverse    = { workspace = true }
oxc_semantic    = { workspace = true }

dashmap          = { workspace = true }
indexmap         = { workspace = true }
serde            = { workspace = true, features = ["derive"] }
serde_json       = { workspace = true }
ropey            = { workspace = true }
rustc-hash       = { workspace = true }
oxc-browserslist = { workspace = true }

[dev-dependencies]
oxc_parser  = { workspace = true }
oxc_codegen = { workspace = true }

[features]
default = []
wasm    = ["oxc-browserslist/wasm_bindgen"]
