[package]
name                   = "oxc_transformer"
version                = "0.2.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lib]
doctest = false

[dependencies]
oxc_ast       = { workspace = true }
oxc_span      = { workspace = true }
oxc_allocator = { workspace = true }
oxc_syntax    = { workspace = true }
oxc_semantic  = { workspace = true }

serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
oxc_parser  = { workspace = true }
oxc_codegen = { workspace = true }
