[package]
name                   = "oxc_span"
version                = "0.19.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator = { workspace = true }

miette      = { workspace = true }
compact_str = { workspace = true }

tsify        = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
serde        = { workspace = true, features = ["derive"], optional = true }

[features]
default   = []
serialize = ["compact_str/serde", "dep:serde", "dep:tsify", "dep:wasm-bindgen"]
