[package]
name                   = "oxc_span"
version                = "0.0.7"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[features]
default = []
serde   = ["dep:serde", "compact_str/serde"]

[dependencies]
miette      = { workspace = true }
compact_str = { workspace = true }

serde = { workspace = true, features = ["derive"], optional = true }
