[package]
name                   = "oxc_transform_napi"
version                = "0.23.0"
publish                = true
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "lib"]
test       = false
doctest    = false

[dependencies]
oxc_allocator             = { workspace = true }
oxc_parser                = { workspace = true }
oxc_span                  = { workspace = true }
oxc_codegen               = { workspace = true }
oxc_isolated_declarations = { workspace = true }
oxc_transformer           = { workspace = true }
oxc_diagnostics           = { workspace = true }

napi        = { workspace = true }
napi-derive = { workspace = true }

[package.metadata.cargo-shear]
ignored = ["napi"]

[build-dependencies]
napi-build = { workspace = true }
