[package]
name = "oxc_transform_conformance"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
publish = false
repository.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[bin]]
name = "oxc_transform_conformance"
test = false
doctest = false

[dependencies]
oxc = { workspace = true, features = ["full"] }
oxc_tasks_common = { workspace = true }
oxc_tasks_transform_checker = { workspace = true }

cow-utils = { workspace = true }
indexmap = { workspace = true }
pico-args = { workspace = true }
walkdir = { workspace = true }
