[package]
name              = "oxc_tasks_common"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[dependencies]
project-root = { workspace = true }

ureq = { workspace = true }
url  = { workspace = true }
