[package]
name              = "oxc_tasks_common"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[lib]
test    = false
doctest = false

[dependencies]
oxc_syntax = { workspace = true, features = ["serde"] }

project-root = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }

ureq = { workspace = true }
url  = { workspace = true }
