[package]
name              = "oxc_tasks_common"
version           = "0.0.0"
publish           = false
edition.workspace = true

[dependencies]
project-root = { workspace = true }

ureq = "2.6.2"
url  = "2.3.1"
