[package]
name              = "oxc_tasks_common"
version           = "0.0.0"
publish           = false
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
test    = false
doctest = false

[dependencies]
console    = { workspace = true }
oxc_syntax = { workspace = true, features = ["serialize"] }

project-root = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
similar      = { workspace = true }

ureq = { workspace = true, features = ["tls", "json"] }
url  = { workspace = true }
