[package]
name = "oxc_syntax"
version = "0.32.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = ["/src"]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast_macros = { workspace = true }
oxc_estree = { workspace = true }
oxc_index = { workspace = true }
oxc_span = { workspace = true }

assert-unchecked = { workspace = true }
bitflags = { workspace = true }
dashmap = { workspace = true }
nonmax = { workspace = true }
phf = { workspace = true, features = ["macros"] }
rustc-hash = { workspace = true }
unicode-id-start = { workspace = true }

ryu-js = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
wasm-bindgen = { workspace = true, optional = true }

[features]
default = []
to_js_string = ["dep:ryu-js"]
serialize = ["bitflags/serde", "dep:serde", "dep:wasm-bindgen", "oxc_index/serialize"]

[package.metadata.cargo-shear]
# We use `oxc_ast_macros::CloneIn` which expands to use `oxc_allocator`.
# To fix this we have to expose `CloneIn` through `oxc_allocator`
# (and probably move it to `oxc_allocator_derive`).
ignored = ["oxc_allocator"]
