[package]
name                  = "oxc_syntax"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[features]
default = []
serde   = ["dep:serde"]

[dependencies]
oxc_index        = { workspace = true }
oxc_span         = { workspace = true }

unicode-id-start = { workspace = true }
serde            = { workspace = true, features = ["derive"], optional = true }
bitflags         = { workspace = true }
rustc-hash       = { workspace = true }
