[package]
name = "oxc_semantic"
version = "0.0.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oxc_ast = { path = "../oxc_ast" }
oxc_diagnostics = { path = "../oxc_diagnostics" }

indextree = { workspace = true }
bitflags = { workspace = true }
rustc-hash = { workspace = true }

[dev_dependencies]
oxc_parser = { path = "../oxc_parser" }
oxc_allocator = { path = "../oxc_allocator" }
