[package]
name                   = "oxc_semantic"
version                = "0.10.0"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
oxc_span        = { workspace = true }
oxc_ast         = { workspace = true }
oxc_syntax      = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_index       = { workspace = true }
oxc_allocator   = { workspace = true }

indexmap   = { workspace = true }
phf        = { workspace = true, features = ["macros"] }
rustc-hash = { workspace = true }
serde      = { workspace = true, features = ["derive"], optional = true }
petgraph   = { workspace = true }

tsify        = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
oxc_parser = { workspace = true }

itertools  = { workspace = true }
indexmap   = { workspace = true }
insta      = { workspace = true, features = ["glob"] }
phf        = { workspace = true, features = ["macros"] }
rustc-hash = { workspace = true }

[features]
default   = []
serialize = ["dep:serde", "oxc_span/serialize", "oxc_syntax/serialize", "dep:tsify", "dep:wasm-bindgen"]
