[package]
name                  = "oxc_semantic"
version               = "0.0.6"
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_ast         = { workspace = true }
oxc_diagnostics = { workspace = true }

indextree   = { workspace = true }
bitflags    = { workspace = true }
rustc-hash  = { workspace = true }
once_cell   = { workspace = true }
compact_str = { workspace = true }
phf         = { workspace = true, features = ["macros"] }

[dev_dependencies]
oxc_parser    = { workspace = true }
oxc_allocator = { workspace = true }
