[package]
name                   = "oxc_allocator"
version                = "0.24.0"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
bumpalo        = { workspace = true, features = ["allocator-api2", "collections"] }
allocator-api2 = { workspace = true }

serde = { workspace = true, optional = true }

[dev-dependencies]
serde      = { workspace = true }
serde_json = { workspace = true }

[features]
serialize = ["dep:serde"]
