[package]
name = "oxc_isolated_declarations"
version = "0.31.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
include = [
  "/examples",
  "/src",
]
keywords.workspace = true
license.workspace = true
publish = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true

[lints]
workspace = true

[lib]
doctest = false
test = false

[dependencies]
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_diagnostics = { workspace = true }
oxc_span = { workspace = true }
oxc_syntax = { workspace = true, features = ["to_js_string"] }
oxc_syntax_operations = { workspace = true }

bitflags = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["glob"] }
oxc_codegen = { workspace = true }
oxc_parser = { workspace = true }
