[package]
name                  = "oxc_benchmark"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[lints]
workspace = true

[lib]
test    = false
bench   = false
doctest = false

[[bench]]
name    = "lexer"
harness = false

[[bench]]
name    = "parser"
harness = false

[[bench]]
name    = "transformer"
harness = false

[[bench]]
name    = "semantic"
harness = false

[[bench]]
name    = "linter"
harness = false

[[bench]]
name    = "codegen_sourcemap"
harness = false

[[bench]]
name    = "sourcemap"
harness = false

# Broken
# [[bench]]
# name    = "prettier"
# harness = false

[[bench]]
name    = "minifier"
harness = false

# Only run in CI
[[bench]]
name    = "parser_napi"
harness = false
bench   = false

[dependencies]
# All optional as `parser_napi` pseudo-benchmark doesn't need any of them,
# and including them in compilation adds 1 minute to building that benchmark on CI.
# See `tasks/benchmark/benches/parser_napi.rs`.
oxc_allocator    = { workspace = true, optional = true }
oxc_linter       = { workspace = true, optional = true }
oxc_minifier     = { workspace = true, optional = true }
oxc_parser       = { workspace = true, features = ["benchmarking"], optional = true }
oxc_prettier     = { workspace = true, optional = true }
oxc_semantic     = { workspace = true, optional = true }
oxc_span         = { workspace = true, optional = true }
oxc_tasks_common = { workspace = true, optional = true }
oxc_transformer  = { workspace = true, optional = true }
oxc_codegen      = { workspace = true, optional = true }
oxc_sourcemap    = { workspace = true, optional = true }

criterion  = { package = "criterion2", version = "0.6.0", default-features = false }
serde      = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = [
  "dep:oxc_allocator",
  "dep:oxc_linter",
  "dep:oxc_minifier",
  "dep:oxc_parser",
  "dep:oxc_prettier",
  "dep:oxc_semantic",
  "dep:oxc_span",
  "dep:oxc_tasks_common",
  "dep:oxc_transformer",
  "dep:oxc_codegen",
  "dep:oxc_sourcemap",
]
codspeed = ["criterion/codspeed"]
codspeed_napi = ["criterion/codspeed", "dep:serde", "dep:serde_json"]
