[package]
name                  = "oxc_benchmark"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[lints]
workspace = true

[lib]
test    = false
bench   = false
doctest = false

[[bench]]
name    = "lexer"
harness = false

[[bench]]
name    = "parser"
harness = false

[[bench]]
name    = "transformer"
harness = false

[[bench]]
name    = "semantic"
harness = false

[[bench]]
name    = "linter"
harness = false

# Broken
# [[bench]]
# name    = "prettier"
# harness = false

[[bench]]
name    = "minifier"
harness = false

[dependencies]
oxc_allocator    = { workspace = true }
oxc_linter       = { workspace = true }
oxc_minifier     = { workspace = true }
oxc_parser       = { workspace = true, features = ["benchmarking"] }
oxc_prettier     = { workspace = true }
oxc_semantic     = { workspace = true }
oxc_span         = { workspace = true }
oxc_tasks_common = { workspace = true }
oxc_transformer  = { workspace = true }

criterion                 = { workspace = true }
codspeed-criterion-compat = { workspace = true, optional = true }

[features]
codspeed = ["codspeed-criterion-compat"]
