[package]
name                  = "oxc_benchmark"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[lib]
bench   = false
doctest = false

[[bench]]
name    = "parser"
harness = false

[[bench]]
name    = "transformer"
harness = false

[[bench]]
name    = "semantic"
harness = false

[[bench]]
name    = "linter"
harness = false

[[bench]]
name    = "prettier"
harness = false

[[bench]]
name    = "minifier"
harness = false

[[bench]]
name    = "resolver"
harness = false

[dependencies]
oxc_allocator    = { workspace = true }
oxc_linter       = { workspace = true }
oxc_minifier     = { workspace = true }
oxc_parser       = { workspace = true }
oxc_prettier      = { workspace = true }
oxc_resolver     = { workspace = true }
oxc_semantic     = { workspace = true }
oxc_span         = { workspace = true }
oxc_tasks_common = { workspace = true }
oxc_transformer  = { workspace = true }

rayon                     = { workspace = true }
criterion                 = { workspace = true }
codspeed-criterion-compat = { workspace = true, optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
mimalloc = { workspace = true }

[features]
codspeed = ["codspeed-criterion-compat"]
