[package]
name = "oxc_printer"
version = "0.0.2"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oxc_allocator = {  workspace = true  }
oxc_ast = {  workspace = true  }

[dev_dependencies]
oxc_parser = {  workspace = true  }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
