[package]
name = "javascript_globals"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "javascript_globals"
test = false
doctest = false

[dependencies]
handlebars = { workspace = true }
oxc_tasks_common = { workspace = true }

lazy_static = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
