[package]
name                   = "oxc_sourcemap"
version                = "0.12.1"
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true
categories.workspace   = true
include                = ["/src"]

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
rustc-hash  = { workspace = true }
rayon       = { workspace = true }
serde       = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true }
base64-simd = "0.7"
