name: autofix.ci # For security reasons, the workflow in which the autofix.ci action is used must be named "autofix.ci".

permissions: {}

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "!.github/workflows/ci.yml"
      - "!.github/actions/clone-submodules/action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - uses: oxc-project/setup-rust@ecabb7322a2ba5aeedb3612d2a40b86a85cee235 # v1.0.11
        with:
          restore-cache: true
          cache-key: warm
          tools: just,cargo-shear@1.9.0
          components: rustfmt

      - name: cargo-shear
        id: shear
        shell: bash
        run: |
          if ! cargo shear --fix; then
            echo "shear=true" >> $GITHUB_OUTPUT
          fi

      - name: Check and update lock file
        run: cargo check --workspace --all-features --all-targets
        if: ${{ steps.shear.outputs.shear == 'true' }}

      - run: just fmt

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with:
          fail-fast: false
