# Run `cargo-llvm-lines` for finding out bloat generic functions

name: Cargo LLVM Lines

permissions: {}

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  bloat:
    name: Cargo LLVM Lines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: oxc-project/setup-rust@704e1648ce532a12b4d6fb98db0ba10afa3ae879 # v1.0.13

      - name: Install cargo-llvm-lines
        uses: taiki-e/install-action@68675c5a5f1a6950c3975d33f3ae0ef155e5bf3d # v2.68.15
        with:
          tool: cargo-llvm-lines

      - name: Run
        run: cargo llvm-lines -p oxc_parser | head -20 > $GITHUB_STEP_SUMMARY
