name: VSCode CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "editors/vscode/**"
      - ".github/workflows/ci_vscode.yml"
  push:
    branches:
      - main
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "editors/vscode/**"
      - ".github/workflows/ci_vscode.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    name: Test VSCode
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Type-Check VSCode
        working-directory: editors/vscode
        run: pnpm run type-check

      - name: Build Language Server
        working-directory: editors/vscode
        run: pnpm run server:build:debug

      - name: Compile VSCode
        working-directory: editors/vscode
        run: pnpm run compile

      - name: Test VSCode
        working-directory: editors/vscode
        run: xvfb-run -a pnpm run test
