name: CI VSCode

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "editors/vscode/**"
      - ".github/worfkflows/ci_vscode.yml"
  push:
    branches:
      - main
      - "renovate/**"
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "editors/vscode/**"
      - ".github/worfkflows/ci_vscode.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: ./.github/actions/pnpm

      - name: Compile VSCode
        working-directory: editors/vscode
        run: pnpm run compile

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: ./.github/actions/pnpm

      - name: Lint VSCode
        working-directory: editors/vscode
        run: pnpm run lint

  type-check:
    name: Type-Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: ./.github/actions/pnpm

      - name: Type-Check VSCode
        working-directory: editors/vscode
        run: pnpm run type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: ./.github/actions/pnpm

      - name: Test VSCode
        working-directory: editors/vscode
        run: xvfb-run -a pnpm run test
