name: VSCode CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "editors/vscode/**"
      - "tasks/vscode_docs/**"
      - ".github/workflows/ci_vscode.yml"
  push:
    branches:
      - main
    paths:
      - "pnpm-lock.yaml"
      - "crates/oxc_language_server/**"
      - "apps/oxlint/src/lsp.rs"
      - "apps/oxfmt/src/lsp/**"
      - "editors/vscode/**"
      - "tasks/vscode_docs/**"
      - ".github/workflows/ci_vscode.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    name: Test VSCode
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: vscode

      - name: Check VSCode README is up-to-date
        run: |
          cargo run -p vscode_docs update
          pnpm fmt
          git diff --exit-code

      - name: Build oxlint (with napi)
        working-directory: editors/vscode
        run: pnpm run oxlint:build:debug

      - name: Build oxfmt (with napi)
        working-directory: editors/vscode
        run: pnpm run oxfmt:build:debug

      - name: Compile VSCode
        working-directory: editors/vscode
        run: pnpm run compile

      - name: Test VSCode
        working-directory: editors/vscode
        run: xvfb-run -a pnpm run test
