name: Conformance

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/package.json'
      - 'npm/**'
      - 'website/**'
      - 'crates/oxc/**'
      - 'crates/oxc_cli/**'
      - 'crates/oxc_linter/**'
      - 'crates/oxc_type_synthesis/**'
      - 'crates/oxc_wasm/**'
      - 'crates/oxc_prettier/**'
      - 'tasks/prettier_conformance/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/package.json'
      - 'npm/**'
      - 'website/**'
      - 'crates/oxc/**'
      - 'crates/oxc_cli/**'
      - 'crates/oxc_linter/**'
      - 'crates/oxc_type_synthesis/**'
      - 'crates/oxc_wasm/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  conformance:
    name: Conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup

      - name: Clone submodules
        uses: ./.github/actions/clone-submodules

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Coverage
        run: just coverage

      - name: Check for snapshot diff
        run: git diff --exit-code
