name: Miri

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "crates/oxc_allocator/**"
      - "crates/oxc_ast/src/utf8_to_utf16.rs"
      - "crates/oxc_ast/src/generated/utf8_to_utf16_converter.rs"
      - "crates/oxc_data_structures/**"
      - "crates/oxc_parser/**"
      - "crates/oxc_traverse/**"
      - ".github/workflows/miri.yml"
  push:
    branches:
      - main
    paths:
      - "crates/oxc_allocator/**"
      - "crates/oxc_ast/src/utf8_to_utf16.rs"
      - "crates/oxc_ast/src/generated/utf8_to_utf16_converter.rs"
      - "crates/oxc_data_structures/**"
      - "crates/oxc_parser/**"
      - "crates/oxc_traverse/**"
      - ".github/workflows/miri.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      # FIXME: cargo-miri is broken on nightly-2026-02-12.
      # https://github.com/rust-lang/miri/issues/4855
      MIRI_TOOLCHAIN: nightly-2026-02-11
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          cache-key: miri
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Install Miri
        run: |
          rustup toolchain install "${MIRI_TOOLCHAIN}" --component miri
          cargo +"${MIRI_TOOLCHAIN}" miri setup

      # `--lib --bins --tests` omits doctests, which Miri can't run
      # https://github.com/oxc-project/oxc/pull/11092
      - name: Test with Miri
        run: |
          cargo +"${MIRI_TOOLCHAIN}" miri test --lib --bins --tests --all-features -p oxc_allocator -p oxc_ast -p oxc_data_structures
          cargo +"${MIRI_TOOLCHAIN}" miri test --lib --bins --tests -p oxc_parser -p oxc_transformer
