name: Miri

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "crates/oxc_allocator/**"
      - "crates/oxc_ast/src/utf8_to_utf16.rs"
      - "crates/oxc_ast/src/generated/utf8_to_utf16_converter.rs"
      - "crates/oxc_data_structures/**"
      - "crates/oxc_parser/**"
      - "crates/oxc_traverse/**"
      - ".github/workflows/miri.yml"
  push:
    branches:
      - main
    paths:
      - "crates/oxc_allocator/**"
      - "crates/oxc_ast/src/utf8_to_utf16.rs"
      - "crates/oxc_ast/src/generated/utf8_to_utf16_converter.rs"
      - "crates/oxc_data_structures/**"
      - "crates/oxc_parser/**"
      - "crates/oxc_traverse/**"
      - ".github/workflows/miri.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          cache-key: miri
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      # `--lib --bins --tests` omits doctests, which Miri can't run
      # https://github.com/oxc-project/oxc/pull/11092
      - name: Test with Miri
        run: |
          cargo miri test --lib --bins --tests --all-features -p oxc_allocator -p oxc_ast -p oxc_data_structures
          cargo miri test --lib --bins --tests -p oxc_parser -p oxc_transformer
