name: Prepare Release Crates

permissions: {}

on:
  workflow_dispatch:
  schedule:
    # Triggers every Monday at 5pm Shanghai time (9am UTC)
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@afad4df3ab3122b166e8226ac83be4d981fb64e8 # v1.3.2
      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          cache-key: warm
          tools: cargo-release-oxc
      - run: cargo ck
      - run: cargo release-oxc publish --release crates --dry-run # zizmor: ignore[use-trusted-publishing]

  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
      version: ${{ steps.run.outputs.CRATES_VERSION }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          cache-key: warm
          tools: cargo-release-oxc

      - name: Run
        id: run
        run: |
          cargo ck
          cargo release-oxc update --release crates
          echo "CRATES_VERSION=$(cat ./target/CRATES_VERSION)" >> $GITHUB_OUTPUT

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      # Run NAPI-RS build, because NAPI-RS uses version from `package.json` in the bindings file,
      # which is committed to the repo. The version has just been bumped in previous step.
      # We don't use the compiled `.node` binary, so only do a development build, as it's faster.
      - name: Rebuild NAPI packages bindings
        run: |
          pnpm --filter oxc-minify run build-dev
          pnpm --filter oxc-parser run build-dev
          pnpm --filter oxc-transform run build-dev

      - name: Update Cargo.lock
        run: cargo check

      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        id: pr
        with:
          # bot account with PAT required for triggering workflow runs
          # See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ secrets.OXC_BOT_PAT }}
          commit-message: "release(crates): oxc v${{ steps.run.outputs.CRATES_VERSION }}"
          title: "release(crates): oxc v${{ steps.run.outputs.CRATES_VERSION }}"
          branch: release/crates
          branch-suffix: timestamp
          base: main
          body-path: ./target/CRATES_CHANGELOG
          assignees: Boshen

  ecosystem-ci:
    needs: prepare
    name: Trigger Monitor Oxc
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: taiki-e/checkout-action@afad4df3ab3122b166e8226ac83be4d981fb64e8 # v1.3.2

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.prepare.outputs.pull-request-number }}
          body: Triggering Monitor Oxc https://github.com/oxc-project/monitor-oxc/actions/workflows/ci.yml

      - uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        with:
          repo: oxc-project/monitor-oxc
          workflow: ci.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "issue-number": "${{ needs.prepare.outputs.pull-request-number }}", "comment-id": "${{ steps.comment.outputs.comment-id }}" }'
