name: Prepare Release Crates

permissions: {}

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1
      - uses: oxc-project/setup-rust@1ff88fdaffd6ae35c0fb32ccc159340b37d0beac # v1.0.7
        with:
          cache-key: warm
          tools: cargo-release-oxc
      - run: cargo ck
      - run: cargo release-oxc publish --release crates --dry-run

  prepare:
    needs: check
    name: Prepare Release Crates
    uses: ./.github/workflows/reusable_prepare_release.yml
    with:
      name: crates
    secrets:
      OXC_BOT_PAT: ${{ secrets.OXC_BOT_PAT }}

  ecosystem-ci:
    needs: prepare
    name: Trigger Monitor Oxc
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        id: comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.prepare.outputs.pull-request-number }}
          body: Triggering Monitor Oxc https://github.com/oxc-project/monitor-oxc/actions/workflows/ci.yml

      - uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        with:
          repo: oxc-project/monitor-oxc
          workflow: ci.yml
          token: ${{ secrets.OXC_BOT_PAT }}
          ref: main
          inputs: '{ "issue-number": "${{ needs.prepare.outputs.pull-request-number }}", "comment-id": "${{ steps.comment.outputs.comment-id }}" }'
