name: Release NAPI Transform

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - napi/transform/package.json
      - .github/workflows/release_napi_transform.yml
      - .github/workflows/reusable_release_napi.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository == 'oxc-project/oxc'
    name: Release NAPI Transform
    uses: ./.github/workflows/reusable_release_napi.yml
    with:
      name: transform
    permissions:
      id-token: write # for `pnpm publish --provenance`
