name: Release Crates

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - crates/oxc/Cargo.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release crates
    runs-on: ubuntu-latest
    permissions:
      contents: write # For git tag push
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ secrets.OXC_BOT_PAT }}
          fetch-depth: 0 # for changelog
          persist-credentials: true

      - uses: oxc-project/setup-rust@ecabb7322a2ba5aeedb3612d2a40b86a85cee235 # v1.0.11
        with:
          cache-key: warm
          tools: cargo-release-oxc

      - run: cargo ck

      - name: Generate changelog
        run: |
          mkdir -p target
          cargo release-oxc changelog --release crates

      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth

      - name: Run
        id: run
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          cargo release-oxc publish --release crates
          echo "TAG=$(cat ./target/CRATES_VERSION)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          body_path: ./target/CRATES_CHANGELOG
          name: oxc ${{ steps.run.outputs.TAG }}
          tag_name: ${{ steps.run.outputs.TAG }}
          target_commitish: ${{ github.sha }}
          draft: false
          make_latest: false # latest is reserved for apps
