name: Release @oxc-project/runtime

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - npm/runtime/package.json
      - .github/workflows/release_runtime.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check version
    runs-on: ubuntu-slim
    outputs:
      version: ${{ steps.check.outputs.version }}
      version_changed: ${{ steps.check.outputs.version_changed }}
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0
      - uses: ./.github/actions/check-version
        id: check
        with:
          file-name: npm/runtime/package.json
          file-url: https://unpkg.com/@oxc-project/runtime/package.json

  build:
    needs: check
    if: needs.check.outputs.version_changed == 'true'
    name: Release @oxc-project/runtime
    runs-on: ubuntu-slim
    permissions:
      id-token: write # for `pnpm publish --provenance`
    steps:
      - uses: taiki-e/checkout-action@3ab630d442e198ebb0ca30872832406ca01c46eb # v1.4.0

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      - run: npm install -g npm@latest # For trusted publishing support

      # Trusted publishing is configured, publish token is not required.
      - name: Trusted Publish
        working-directory: npm/runtime
        run: pnpm publish --provenance --access public --no-git-checks
