name: Website

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 00:00 every day
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'website/**'
      - '.github/workflows/website.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  website:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@v1

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          shared-key: 'wasm'

      - name: Install pnpm
        working-directory: website
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: ./website/package.json
          cache: pnpm

      - name: Build
        working-directory: website
        run: |
          pnpm install
          pnpm run build

      - name: Deploy Website
        if: ${{ github.ref_name == 'main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          publish_branch: gh-pages
